### ISSUE TITLE
Kan ikke indtaste mit kodeord.

### ISSUE THREAD

**Issue by ghost** [MJoergen/lectio-dl#4]
Kan ikke få lov til at indtaste mit kodeord, der sker ikke noget når jeg prøver at taste nogen som helst tegn ind. 

Har prøvet at se om den bare ikke viste tegnene, men den sagde koden stadig var forkert.

**Comment by MJoergen** [comment]
Det er rigtigt, at programmet skriver/viser ikke noget, mens man taster sit kodeord ind. Så højst sandsynligt er det en tastefejl under indtastning.

Bruger du danske tegn (æøå) i dit kodeord? Det kan måske give problemer. I så fald, gå ind i lectio og lav dit kodeord om først, og prøv så igen.

**Comment by ghost** [comment]
Har nu forsøgt utallige gange uden held.
Har ingen danske tegn i mit kodeord, og mistænker derfor brugernavnet til måske at være en fejlkilde. Der er et mellemrum i, hvis det kan give problemer.
Kan ikke rigtig få programmet til at virke.

**Comment by MJoergen** [comment]
Øv, det er godt nok træls. Jeg kan desværre ikke se, hvorfor det ikke virker for dig.

Kan du fortælle lidt mere om dine computer? Er det Mac eller Windows? Og hvilken version?

Virker programmet for nogle af dine kolleger?

**Comment by ghost** [comment]
Jeg har en Windows computer, der kører Windows 10 Pro. 
Jeg har ikke hørt, at der er nogen som har fået det til at virke endnu.

**Comment by MJoergen** [comment]
Hvad hedder din skole?

**Comment by ghost** [comment]
Teknisk Gymnasium Sønderjylland. Før hed det EUC syd Haderslev
Ved ikke om det er specielt med mellemrum i brugernavnet.

**Comment by MJoergen** [comment]
Der er også en anden bruger fra din skole herinde, som heller ikke kan logge ind.

Jeg kan ikke umiddelbart se, hvorfor det ikke virker.

Jeg vil gerne hjælpe dig og andre, men så skal jeg bruge dit brugernavn og kodeord. Tror du, at du kan sende det til mig på sms? Når det så virker, så kan du altid lave dit kodeord om bagefter.

Mit mobilnummer er 61362938.

Alternativt kan du sende det til min arbejds-mail: mj@msg-gym.dk

**Comment by MJoergen** [comment]
Jeg har opdateret programmet, så det også virker for elever. Jeg lukker derfor denne "issue".
