### ISSUE TITLE
kan ikke skrive kode ordet ind/ det viser sig ikke

### ISSUE THREAD

**Issue by marc1233** [MJoergen/lectio-dl#5]
hey
den siger der ikke er nogen bruger eller at kodeordet er forkert, det er det dog ikke. 
skulle gerne bruge disse filer næste år, og der er andre som har det samme problem, 
pc= windows 7

**Comment by MJoergen** [comment]
Hvad hedder din skole?

2016-06-12 22:44 GMT+02:00 marc1233 notifications@github.com:

**Comment by marc1233** [comment]
Teknisk Gymnasium Sønderjylland

**Comment by MJoergen** [comment]
Der er også en anden bruger fra din skole herinde, som heller ikke kan logge ind.

Jeg kan ikke umiddelbart se, hvorfor det ikke virker.

Jeg vil gerne hjælpe dig og andre, men så skal jeg bruge dit brugernavn og kodeord. Tror du, at du kan sende det til mig på sms? Når det så virker, så kan du altid lave dit kodeord om bagefter.

Mit mobilnummer er 61362938.

Alternativt kan du sende det til min arbejds-mail: mj@msg-gym.dk

**Comment by MJoergen** [comment]
Programmet er nu opdateret, så det også virker med elever. Jeg lukker denne "issue".
