### ISSUE TITLE
Kan ikke logge ind

### ISSUE THREAD

**Issue by birgittemoebjerg** [MJoergen/lectio-dl#6]
den lille sorte skærm virker fint - lige til den skal modtage mit password. Der kan man slet ikke skrive noget
![image](https://cloud.githubusercontent.com/assets/19979557/16125302/67a2d78c-33f3-11e6-92c1-2b16ffb7c16e.png)
Gad vide - om det skærmdump kan ses ;-)

Jeg valgte udgaven til windows 7, men har faktisk windows 8

**Comment by MJoergen** [comment]
Det er rigtigt, at programmet ikke viser noget (f.eks. *'er). Men den
registrerer dine task-tryk alligevel.

Når du har indtastet dit kodeord, så tryk Enter, og så skulle det virke.

2016-06-16 18:53 GMT+02:00 birgittemoebjerg notifications@github.com:

**Comment by birgittemoebjerg** [comment]
Fantastisk - det virkede nu. Men når der ikke står noget, tror man jo, at programmet ikke tager imod.
Tak
